# Generated by Django 5.1 on 2024-08-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_applicant_image_alter_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='static/media/'),
        ),
    ]
