# Generated by Django 5.1 on 2024-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_applicant_full_name_alter_applicant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(default='static/images/user.jpg', upload_to='images/'),
        ),
    ]
