# Generated by Django 5.1 on 2024-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, default='static/images/user.jpg', null=True, upload_to='images/'),
        ),
    ]
